/* Models Data */

INSERT INTO `buybackb_testcis440`.`models` (`ModelId`, `Brand`, `Model`, `Size`, `Color`, `Carrier`) 
	VALUES ('1', 'iPhone', '4', '16', NULL, 'ATT'),
		   ('2', 'iPhone', '4', '32', NULL, 'ATT'),
		   ('3', 'iPhone', '4S', '16', NULL, 'ATT'),
		   ('4', 'iPhone', '4S', '32', NULL, 'ATT'),
		   ('5', 'iPhone', '4S', '64', NULL, 'ATT'),
		   ('6', 'iPhone', '5', '16', NULL, 'ATT'),
		   ('7', 'iPhone', '5', '32', NULL, 'ATT'),
		   ('8', 'iPhone', '5', '64', NULL, 'ATT'),
		   ('9', 'iPhone', '5C', '16', NULL, 'ATT'),
		   ('10', 'iPhone', '5C', '32', NULL, 'ATT'),
		   ('11', 'iPhone', '5S', '16', NULL, 'ATT'),
		   ('12', 'iPhone', '5S', '32', NULL, 'ATT'),
		   ('13', 'iPhone', '5S', '64', NULL, 'ATT'),
		   ('14', 'iPhone', '6', '16', NULL, 'ATT'),
		   ('15', 'iPhone', '6', '64', NULL, 'ATT'),
		   ('16', 'iPhone', '6', '128', NULL, 'ATT'),
		   ('17', 'iPhone', '6+', '16', NULL, 'ATT'),
		   ('18', 'iPhone', '6+', '64', NULL, 'ATT'),
		   ('19', 'iPhone', '6+', '128', NULL, 'ATT'),
		   
		   
		   ('20', 'samsung', 'S4', '16', NULL, 'ATT'),
		   ('21', 'samsung', 'S4', '32', NULL, 'ATT'),
		   ('22', 'samsung', 'S4', '64', NULL, 'ATT'),
		   ('23', 'samsung', 'S4 Mini', '16', NULL, 'ATT'),
		   ('24', 'samsung', 'S5', '16', NULL, 'ATT'),
		   ('25', 'samsung', 'S5', '32', NULL, 'ATT'),
		   ('26', 'samsung', 'S5 Mini', '16', NULL, 'ATT'),
		   ('27', 'samsung', 'S5 Sport', '16', NULL, 'ATT'),
		   ('28', 'samsung', 'S5 Sport', '32', NULL, 'ATT'),
		   ('29', 'samsung', 'Note 4', '32', NULL, 'ATT'),
		   ('30', 'samsung', 'Note 4 Edge', '32', NULL, 'ATT')
		   
		   ('31', 'iPhone', '4', '16', NULL, 'TMOBILE'),
		   ('32', 'iPhone', '4', '32', NULL, 'TMOBILE'),
		   ('33', 'iPhone', '4S', '16', NULL, 'TMOBILE'),
		   ('34', 'iPhone', '4S', '32', NULL, 'TMOBILE'),
		   ('35', 'iPhone', '4S', '64', NULL, 'TMOBILE'),
		   ('36', 'iPhone', '5', '16', NULL, 'TMOBILE'),
		   ('37', 'iPhone', '5', '32', NULL, 'TMOBILE'),
		   ('38', 'iPhone', '5', '64', NULL, 'TMOBILE'),
		   ('39', 'iPhone', '5C', '16', NULL, 'TMOBILE'),
		   ('40', 'iPhone', '5C', '32', NULL, 'TMOBILE'),
		   ('41', 'iPhone', '5S', '16', NULL, 'TMOBILE'),
		   ('42', 'iPhone', '5S', '32', NULL, 'TMOBILE'),
		   ('43', 'iPhone', '5S', '64', NULL, 'TMOBILE'),
		   ('44', 'iPhone', '6', '16', NULL, 'TMOBILE'),
		   ('45', 'iPhone', '6', '64', NULL, 'TMOBILE'),
		   ('46', 'iPhone', '6', '128', NULL, 'TMOBILE'),
		   ('47', 'iPhone', '6+', '16', NULL, 'TMOBILE'),
		   ('48', 'iPhone', '6+', '64', NULL, 'TMOBILE'),
		   ('49', 'iPhone', '6+', '128', NULL, 'TMOBILE'),

	
		   ('51', 'iPhone', '4', '16', NULL, 'VERIZON'),
		   ('52', 'iPhone', '4', '32', NULL, 'VERIZON'),
		   ('53', 'iPhone', '4S', '16', NULL, 'VERIZON'),
		   ('54', 'iPhone', '4S', '32', NULL, 'VERIZON'),
		   ('55', 'iPhone', '4S', '64', NULL, 'VERIZON'),
		   ('56', 'iPhone', '5', '16', NULL, 'VERIZON'),
		   ('57', 'iPhone', '5', '32', NULL, 'VERIZON'),
		   ('58', 'iPhone', '5', '64', NULL, 'VERIZON'),
		   ('59', 'iPhone', '5C', '16', NULL, 'VERIZON'),
		   ('60', 'iPhone', '5C', '32', NULL, 'VERIZON'),
		   ('61', 'iPhone', '5S', '16', NULL, 'VERIZON'),
		   ('62', 'iPhone', '5S', '32', NULL, 'VERIZON'),
		   ('63', 'iPhone', '5S', '64', NULL, 'VERIZON'),
		   ('64', 'iPhone', '6', '16', NULL, 'VERIZON'),
		   ('65', 'iPhone', '6', '64', NULL, 'VERIZON'),
		   ('66', 'iPhone', '6', '128', NULL, 'VERIZON'),
		   ('67', 'iPhone', '6+', '16', NULL, 'VERIZON'),
		   ('68', 'iPhone', '6+', '64', NULL, 'VERIZON'),
		   ('69', 'iPhone', '6+', '128', NULL, 'VERIZON'),

		   ('71', 'iPhone', '4', '16', NULL, 'SPRINT'),
		   ('72', 'iPhone', '4', '32', NULL, 'SPRINT'),
		   ('73', 'iPhone', '4S', '16', NULL, 'SPRINT'),
		   ('74', 'iPhone', '4S', '32', NULL, 'SPRINT'),
		   ('75', 'iPhone', '4S', '64', NULL, 'SPRINT'),
		   ('76', 'iPhone', '5', '16', NULL, 'SPRINT'),
		   ('77', 'iPhone', '5', '32', NULL, 'SPRINT'),
		   ('78', 'iPhone', '5', '64', NULL, 'SPRINT'),
		   ('79', 'iPhone', '5C', '16', NULL, 'SPRINT'),
		   ('80', 'iPhone', '5C', '32', NULL, 'SPRINT'),
		   ('81', 'iPhone', '5S', '16', NULL, 'SPRINT'),
		   ('82', 'iPhone', '5S', '32', NULL, 'SPRINT'),
		   ('83', 'iPhone', '5S', '64', NULL, 'SPRINT'),
		   ('84', 'iPhone', '6', '16', NULL, 'SPRINT'),
		   ('85', 'iPhone', '6', '64', NULL, 'SPRINT'),
		   ('86', 'iPhone', '6', '128', NULL, 'SPRINT'),
		   ('87', 'iPhone', '6+', '16', NULL, 'SPRINT'),
		   ('88', 'iPhone', '6+', '64', NULL, 'SPRINT'),
		   ('89', 'iPhone', '6+', '128', NULL, 'SPRINT'),

  	           ('91', 'iPhone', '4', '16', NULL, 'UNLOCKED'),
		   ('92', 'iPhone', '4', '32', NULL, 'UNLOCKED'),
		   ('93', 'iPhone', '4S', '16', NULL, 'UNLOCKED'),
		   ('94', 'iPhone', '4S', '32', NULL, 'UNLOCKED'),
		   ('95', 'iPhone', '4S', '64', NULL, 'UNLOCKED'),
		   ('96', 'iPhone', '5', '16', NULL, 'UNLOCKED'),
		   ('97', 'iPhone', '5', '32', NULL, 'UNLOCKED'),
		   ('98', 'iPhone', '5', '64', NULL, 'UNLOCKED'),
		   ('99', 'iPhone', '5C', '16', NULL, 'UNLOCKED'),
		   ('100', 'iPhone', '5C', '32', NULL, 'UNLOCKED'),
		   ('101', 'iPhone', '5S', '16', NULL, 'UNLOCKED'),
		   ('102', 'iPhone', '5S', '32', NULL, 'UNLOCKED'),
		   ('103', 'iPhone', '5S', '64', NULL, 'UNLOCKED'),
		   ('104', 'iPhone', '6', '16', NULL, 'UNLOCKED'),
		   ('105', 'iPhone', '6', '64', NULL, 'UNLOCKED'),
		   ('106', 'iPhone', '6', '128', NULL, 'UNLOCKED'),
		   ('107', 'iPhone', '6+', '16', NULL, 'UNLOCKED'),
		   ('108', 'iPhone', '6+', '64', NULL, 'UNLOCKED'),
		   ('109', 'iPhone', '6+', '128', NULL, 'UNLOCKED');
		   